// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("../utils.bs.js");
var React = require("react");

function View_home(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "margin-bottom-xl"
                }, Utils.textEl("Home")), React.createElement("p", undefined, Utils.textEl("This is REASONML CRUD example.")), React.createElement("p", undefined, Utils.textEl("Purpose of this project was to study REASONML and find a lean way how to implement common CRUD functionality using simple Company-entity.")));
}

var make = View_home;

exports.make = make;
/* Utils Not a pure module */
