// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../utils.bs.js";
import * as React from "react";

function View_home(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "margin-bottom-xl"
                }, Utils.textEl("Home")), React.createElement("p", undefined, Utils.textEl("This is REASONML CRUD example.")), React.createElement("p", undefined, Utils.textEl("Purpose of this project was to study REASONML and find a lean way how to implement common CRUD functionality using simple Company-entity.")));
}

var make = View_home;

export {
  make ,
  
}
/* Utils Not a pure module */
