// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Company;

var Companies;

var Home;

exports.Company = Company;
exports.Companies = Companies;
exports.Home = Home;
/* No side effect */
