// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "../link.bs.js";
import * as Curry from "../../../../../../usr/local/lib/node_modules/bs-platform/lib/es6/curry.js";
import * as Utils from "../utils.bs.js";
import * as React from "react";
import * as Notify from "../notify.bs.js";
import * as Model_company from "../model/model_company.bs.js";

function renderCompany(company) {
  return React.createElement("div", {
              className: "margin-left-md"
            }, React.createElement("p", undefined, React.createElement("strong", undefined, Utils.textEl("ID: ")), Utils.optIntEl(company.id)), React.createElement("p", undefined, React.createElement("strong", undefined, Utils.textEl("Name: ")), Utils.textEl(company.name)));
}

function View_company(Props) {
  var id = Props.id;
  var match = React.useReducer((function (param, action) {
          return {
                  company: action._0
                };
        }), {
        company: undefined
      });
  var dispatch = match[1];
  React.useEffect((function () {
          Model_company.Api.$$fetch(id).then(function (company) {
                  Curry._1(dispatch, /* Loaded */{
                        _0: company
                      });
                  return Promise.resolve(undefined);
                }).catch(function (_err) {
                Notify.showError("Failed to fetch companies! Check network connection!");
                return Promise.resolve(undefined);
              });
          
        }), []);
  var company = match[0].company;
  var companyContent = company !== undefined ? renderCompany(company) : "Loading company";
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "margin-bottom-lg"
                }, React.createElement(Link.make, {
                      route: /* Companies */1,
                      children: Utils.textEl("< Back")
                    })), React.createElement("h1", {
                  className: "pt-running-text"
                }, Utils.textEl("Company")), React.createElement("div", undefined, companyContent));
}

var make = View_company;

export {
  renderCompany ,
  make ,
  
}
/* Link Not a pure module */
