// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "./link.bs.js";
import * as Curry from "../../../../../usr/local/lib/node_modules/bs-platform/lib/es6/curry.js";
import * as Utils from "./utils.bs.js";
import * as React from "react";
import * as Router from "./router.bs.js";
import * as Core from "@blueprintjs/core";

require("./app.css");

var logo = require("./logo.svg");

function App(Props) {
  var match = React.useReducer((function (param, action) {
          return {
                  mainContent: action._0
                };
        }), {
        mainContent: Router.getInitialPage(undefined)
      });
  var dispatch = match[1];
  React.useEffect((function () {
          var watcherID = Router.init(function (el) {
                return Curry._1(dispatch, /* MainContentChanged */{
                            _0: el
                          });
              });
          return (function (param) {
                    return Router.destroy(watcherID);
                  });
        }), [dispatch]);
  return React.createElement("div", {
              className: "app"
            }, React.createElement(Core.Navbar, {
                  className: "pt-dark",
                  children: null
                }, React.createElement(Core.NavbarGroup, {
                      align: /* Left */0,
                      children: null
                    }, React.createElement(Link.make, {
                          route: /* Home */0,
                          className: "test",
                          children: React.createElement("img", {
                                className: "app-logo",
                                alt: "logo",
                                src: logo
                              })
                        }), React.createElement(Link.make, {
                          route: /* Home */0,
                          className: "pt-navbar-heading pt-button pt-minimal",
                          children: Utils.textEl("REASONML CRUD EXAMPLE")
                        })), React.createElement(Core.NavbarGroup, {
                      align: /* Right */1,
                      children: null
                    }, React.createElement(Link.make, {
                          route: /* Companies */1,
                          className: "pt-button pt-minimal pt-icon-people",
                          children: Utils.textEl("Companies")
                        }), React.createElement(Core.NavbarDivider, {}), React.createElement(Core.Button, {
                          className: "pt-minimal",
                          iconName: "cog"
                        }))), React.createElement("div", {
                  className: "app-content"
                }, match[0].mainContent));
}

var make = App;

export {
  logo ,
  make ,
  
}
/*  Not a pure module */
