// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");

Jest.test("addition", (function (param) {
        return Jest.Expect.toBe(7, Jest.Expect.expect(7));
      }));

/*  Not a pure module */
