// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var defaultHeaders = {
      "Content-Type": "application/json"
    };

function getDefaultHeaders(param) {
  return defaultHeaders;
}

var $$Request = {
  defaultHeaders: defaultHeaders,
  getDefaultHeaders: getDefaultHeaders
};

var FetchError = /* @__PURE__ */Caml_exceptions.create("Common.FetchError");

function statusOk(response) {
  if (response.ok) {
    return Promise.resolve(undefined);
  } else {
    return Promise.reject({
                RE_EXN_ID: FetchError,
                _1: response
              });
  }
}

var $$Response = {
  statusOk: statusOk
};

exports.$$Request = $$Request;
exports.FetchError = FetchError;
exports.$$Response = $$Response;
/* No side effect */
