// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "../../../../../usr/local/lib/node_modules/bs-platform/lib/es6/caml_exceptions.js";

var defaultHeaders = {
      "Content-Type": "application/json"
    };

function getDefaultHeaders(param) {
  return defaultHeaders;
}

var $$Request = {
  defaultHeaders: defaultHeaders,
  getDefaultHeaders: getDefaultHeaders
};

var FetchError = /* @__PURE__ */Caml_exceptions.create("Common.FetchError");

function statusOk(response) {
  if (response.ok) {
    return Promise.resolve(undefined);
  } else {
    return Promise.reject({
                RE_EXN_ID: FetchError,
                _1: response
              });
  }
}

var $$Response = {
  statusOk: statusOk
};

export {
  $$Request ,
  FetchError ,
  $$Response ,
  
}
/* No side effect */
