// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./app.bs.js";
import * as Utils from "./utils.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

require("./index.css");

Utils.registerServiceWorker(undefined);

var root = document.querySelector("#root");

if (root == null) {
  console.log("Coudn't find #root element to mount the React app.");
} else {
  ReactDom.render(React.createElement(App.make, {}), root);
}

export {
  
}
/*  Not a pure module */
