// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core = require("@blueprintjs/core");

var toasterProps = {
  position: /* BOTTOM */7
};

var toaster = Core.Toaster.default(toasterProps);

function showError(text) {
  var props = {
    message: text,
    intent: /* DANGER */4,
    iconName: "warning-sign"
  };
  return toaster.show(props);
}

exports.toasterProps = toasterProps;
exports.toaster = toaster;
exports.showError = showError;
/* toaster Not a pure module */
