// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "@blueprintjs/core";

var toasterProps = {
  position: /* BOTTOM */7
};

var toaster = Core.Toaster(toasterProps);

function showError(text) {
  var props = {
    message: text,
    intent: /* DANGER */4,
    iconName: "warning-sign"
  };
  return toaster.show(props);
}

export {
  toasterProps ,
  toaster ,
  showError ,
  
}
/* toaster Not a pure module */
