// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../../../usr/local/lib/node_modules/bs-platform/lib/es6/curry.js";
import * as Utils from "./utils.bs.js";
import * as React from "react";
import * as Routes from "./routes.bs.js";
import * as View_home from "./view/view_home.bs.js";
import * as View_company from "./view/view_company.bs.js";
import * as View_companies from "./view/view_companies.bs.js";
import * as RescriptReactRouter from "../node_modules/@rescript/react/src/RescriptReactRouter.bs.js";

function getPageFromPath(path) {
  var route = Routes.getRoute(path);
  if (typeof route !== "number") {
    return React.createElement(View_company.make, {
                id: route._0
              });
  }
  switch (route) {
    case /* Home */0 :
        return React.createElement(View_home.make, {});
    case /* Companies */1 :
        return React.createElement(View_companies.make, {});
    case /* NotFound */2 :
        return React.createElement("div", undefined, Utils.textEl("Page not found!"));
    
  }
}

function getInitialPage(param) {
  return getPageFromPath(RescriptReactRouter.dangerouslyGetInitialUrl(undefined, undefined).path);
}

function init(pageChanged) {
  return RescriptReactRouter.watchUrl(function (url) {
              return Curry._1(pageChanged, getPageFromPath(url.path));
            });
}

var destroy = RescriptReactRouter.unwatchUrl;

export {
  getPageFromPath ,
  getInitialPage ,
  init ,
  destroy ,
  
}
/* Utils Not a pure module */
