// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("./utils.bs.js");
var React = require("react");
var Routes = require("./routes.bs.js");
var View_home = require("./view/view_home.bs.js");
var View_company = require("./view/view_company.bs.js");
var View_companies = require("./view/view_companies.bs.js");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.bs.js");

function getPageFromPath(path) {
  var route = Routes.getRoute(path);
  if (typeof route !== "number") {
    return React.createElement(View_company.make, {
                id: route._0
              });
  }
  switch (route) {
    case /* Home */0 :
        return React.createElement(View_home.make, {});
    case /* Companies */1 :
        return React.createElement(View_companies.make, {});
    case /* NotFound */2 :
        return React.createElement("div", undefined, Utils.textEl("Page not found!"));
    
  }
}

function getInitialPage(param) {
  return getPageFromPath(RescriptReactRouter.dangerouslyGetInitialUrl(undefined, undefined).path);
}

function init(pageChanged) {
  return RescriptReactRouter.watchUrl(function (url) {
              return Curry._1(pageChanged, getPageFromPath(url.path));
            });
}

var destroy = RescriptReactRouter.unwatchUrl;

exports.getPageFromPath = getPageFromPath;
exports.getInitialPage = getInitialPage;
exports.init = init;
exports.destroy = destroy;
/* Utils Not a pure module */
